// historyMode-demo/app-main/src/App.vue
<template>
  <div class="main-conatiner">
     <a-menu :selectedKeys="[currentRoute]" mode="inline" theme="dark">
      <a-menu-item 
        v-for="(item) in menus" 
        :key="item.key"
        >
        <router-link :to="item.route">{{item.title}}</router-link>
      </a-menu-item>
     </a-menu>
    <section class="content-wrapper">
      <!-- 主应用渲染区，用于挂载主应用路由触发的组件 -->
      <router-view v-show="$route.name" />

      <!-- 子应用渲染区，用于挂载子应用节点 -->
      <section v-show="!$route.name" id="frame"></section>
    </section>
  </div>
</template>

<script>
export default {
  name: "App",

  data() {
    return {
      menus: [
        {
          key: "Home",
          title: "主页",
          route: "/"
        },
        {
          key: "VueMicroApp",
          title: "Vue 主页",
          route: "/vue/"
        },
        {
          key: "VueMicroAppAbout",
          title: "Vue 关于",
          route: "/vue/about"
        },
        {
          key: "ReactMicroApp",
          title: "React 主页",
          route: "/react/"
        },
        {
          key: "ReactMicroAppAbout",
          title: "React 关于",
          route: "/react/about"
        }
      ]
    }
  },

  computed: {
    currentRoute() {
      const menu = this.menus.find(item => item.route === this.$route.path)
      return menu ? menu.key : "Home"
    }
  },
}
</script>
<style scoped>
#app {
  height: 100%;
  position: relative;
}
.ant-menu {
  position: fixed;
  width: 200px;
  height: 100%;
  bottom: 0;
  left: 0;
}
.content-wrapper {
  margin-left: 200px;
}
</style>

// historyMode-demo/app-react/src/App.js
import React, { Suspense, useState, useEffect } from "react";
import { Menu } from "antd";
import { BrowserRouter as Router, Route, Switch, Link } from "react-router-dom";

import Home from "./pages/home";
import About from "./pages/about";
const BASE_NAME = window.__POWERED_BY_QIANKUN__ ? "/react" : "";

const menus = [
  {
    key: "home",
    route: "/",
    title: "主页",
  },
  {
    key: "about",
    route: "/about",
    title: "关于",
  },
];

const App = () => {
  const [refresh, setRefresh] = useState(0);
  const [selectedKeys, setSelectKeys] = useState(["home"]);
  useEffect(() => {
    const { pathname } = window.location;
    const menu = menus.find((item) => `${BASE_NAME}${item.route}` === pathname);
    setSelectKeys(() => [menu ? menu.key : "home"]);
  }, [refresh]);

  // 设置路由命名空间
  return (
    <Router basename={BASE_NAME}>
      <section>
        <Menu
          onClick={() => setRefresh((refresh) => ++refresh)}
          selectedKeys={selectedKeys}
          mode="horizontal"
        >
          {menus.map((item) => (
            <Menu.Item key={item.key}>
              <Link to={item.route}>{item.title}</Link>
            </Menu.Item>
          ))}
        </Menu>
        <Suspense fallback={null}>
          <Switch>
            <Route exact path="/" component={Home} />
            <Route path="/about" component={About} />
          </Switch>
        </Suspense>
      </section>
    </Router>
  );
};

export default App;
